from sklearn import svm
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier
import numpy as np
from sklearn import svm
import pickle
import cv2
import imutils

SS = ['VMGIRVH WFOB XLNKOVGVW ZMW UFOOB UROOVW NFHG YV HFYNRGGVW FHRMT GSV LMORMV ZKKORXZGRLM HBHGVN YVULIV KN LM GS NZB TFRWVORMVH ULI GSV VMGIRVH GSV DIRGV FK HSLFOW VRGSVI YV HFYNRGGVW RM SRMWR LI VMTORHS',

'RM XZHV HFYNRHHRLM RH RM ZMB LGSVI OZMTFZTV  RG NFHG YV ZXXLNKZMRVW DRGS GIZMHOZGRLM RM VRGSVI SRMWR LI VMTORHS RG XLFOW YV ZM RMWRERWFZO KILQVXG LI Z GVZN KILQVXG  SLDVEVI  RM XZHV LU GVZN  GSV GLGZO',

'GVZN NVNYVIH  RMXOFWRMT GSV GVZN OVZWVI  HSLFOW MLG VCXVVW HRC ML IVUVIVMXV LU GSV RWVMGRGB LU GSV KVIHLM HFYNRGGRMT HSLFOW YV NZWV RM GSV KILKLHZO  RU WLMV HL  RG HSZOO OVZW GL GSV VMGIB TVGGRMT IVQV',

'XGVW RG RH HGILMTOB ZWERHVW MLG GL DZRG GROO GSV XOLHFIV GRNV ULI HFYNRHHRLM LU VMGIRVH  IZRODZBH HSZOO MLG YV IVHKLMHRYOV ULI OZGV MLM IVXVRKG LU VMGIRVH LM ZXXLFMG LU HVIEVI VIILIH GIZUURX GSV XLMGV',

'HGZMGH NZB YV ZHPVW GL KIVHVMG  VOZYLIZGV GSVRI RWVZH YVULIV ZM ZKKILKIRZGV QFIB IZRODZBH NZB WVXRWV GL ZHHLXRZGV DRGS GSV KILKLHVI ULI UFIGSVI WVEVOLKNVMG LU GSV KILKLHVW XLMXVKG RWVZ GSV WVXRHRLM LU',

'GSV VEZOFZGRLM KZMVO ZMW QFIB DROO YV URMZO  ML XLNNFMRXZGRLM DROO YV VMGVIVW DRGS ZMB KVIHLM RM IVOZGRLM GL ZMB WVXRHRLM LU GSV KZMVO LI KILXVHH FMHFXXVHHUFO VMGIRVH HSZOO YV RMGRNZGVW GSILFTS VNZROZ',

'MW NRMRHGIB LU IZRODZBH HSZOO MLG SZEV ZMB IRTSG LEVI GSV HZNV GSV XLNKVGRGRLM RH LKVM GL RMWRERWFZOH ZMW XLNKZMRVH LI RMHGRGFGRLMH  GSV KZIGRXRKZMGH ZIV IVJFRIVW GL YV ZG OVZHG BVZIH LU ZTV  GSV VEZO',

'FZGRLM LU GSV VMGIRVH DROO YV XZIIRVW LFG RM GSIVV HGZTVH  RM GSV URIHG HGZTV VMGIRVH DROO YV HSLIGORHGVW ZUGVI VEZOFZGRLM ZMW GSV HSLIGORHGVW VMGIRVH DROO YV UFIGSVI VEZOFZGVW YB ZM VCKVIG KZMVO LM H',

'HVXLMW HGZTV ULI HVOVXGRLM NLHG KILNRHRMT RWVZH  GSV URMZO    RWVZH DROO YV KIVHVMGVW GL XLNKVGRGRLM XLNNRGGVV DSRXS RH ULINVW YB GSV NRMRHGIB ULI XLMHRWVIZGRLM LU ZDZIWH  HL  DSZG ZIV BLF DZRGRMT ULI',

'ERHRG GSV LUURXRZO DVYHRGV LU QZM YSZTRWZIR GL KZIGRXRKZGV RM GSRH XLNKVGRGRLM WZB YB WZB GSV UIVHS ZRI LU GSV VMERILMNVMG RH TVGGRMT KLOOFGVW YVXZFHV LU GSV NRCRMT LU KZIGRXFOZGVH  YRLOLTRXZO NLOVXFO',

'VH  ZMW LGSVI SZINUFO NZGVIRZOH  HFXS KLOOFGVW ZRI RH XZFHRMT SVZOGS KILYOVNH  WRHVZHVH ZMW WVZGS  ZRI KLOOFGRLM RH LMV LU GSV NLHG RNKLIGZMG VMERILMNVMGZO RHHFVH DSRXS IVJFRIVH GL YV MLGRXVW ZMW HLOE',
'VW YB GSV VUULIGH LU ZOO LU FH  RM LIWVI GL RMXIVZHV ZDZIVMVHH ZNLMT HGFWVMGH ZYLFG GSRH RHHFV  ZRI KLOOFGRLM VHHZB SZH YVXLNV ZM RNKLIGZMG GLKRX ULI GSV VHHZB DIRGRMT XLNKVGRGRLM  HL HGFWVMGH BLF ZIV',

'ZG IRTSG KOZXV  QFHG TL ZSVZW  HFXS VHHZB LM ZRI KLOOFGRLM DROO SVOK BLF GL DRM VHHZB DIRGRMT XLNKVGRGRLM YVXZFHV ZOO ZIV DIRGGVM RM EVIB HRNKOV VMTORHS OZMTFZTV FHRMT VZHB DLIWH  ZRI KLOOFGRLM RH Z N',

'LHG HVIRLFH KILYOVN LU GSV XFIIVMG GRNV ZOO LEVI GSV DLIOW VHKVXRZOOB RM GSV OZITV XRGRVH YVXZFHV LU GSV SFTV OVEVO LU RMWFHGIRZORAZGRLM  GSV IVOVZHV LU HFXS ZRI KLOOFGZMGH RM SVZEB XLMXVMGIZGRLMH HF',

'KZIGRXFOZGVH  HLORW NZGVIRZOH  VGX ZIV TVGGRMT HVGGOVW LEVI GSV XRGB  XZFHRMT ZRI KLOOFGRLM ZMW SVZOGS SZAZIWH GL GSV KVLKOV  OLGH LU WRIGB DZHGVH KILWFXVW YB KVLKOV LM WZROB YZHRH VHKVXRZOOB RM GSV Y',

'RT XRGRVH KLOOFGRMT GSV DSLOV ZGNLHKSVIRX ZRI GL Z TIVZG VCGVMG  ZRI KLOOFGRLM RH GSV NRCRMT LU ZMB SZINUFO HFYHGZMXVH GL GSV ZGNLHKSVIV UIVHS ZRI XZFHRMT SFTV OVEVO LU WZNZTVH  SFNZM SVZOGS WRHLIWVIH',

'IVWFXRMT GSV JFZORGB LU ORUV  VGX  ZRI KLOOFGRLM RH RMXIVZHRMT WZB YB WZB YVXZFHV LU GSV RMXIVZHRMT MFNYVI LU RMWFHGIRVH  HFXS KLOOFGVW ZRI MVEVI IVNZRMH ZG LMV KOZXV SLDVEVI HKIVZW GL DSLOV VMERILMN',

'NVMG ZMW ZUUVXGRMT GSV OREVH LU GSV KVLKOV ZOO GSILFTS GSV DLIOW  WVZGS IZGVH LU GSV SFNZM YVRMTH SZEV YVVM RMXIVZHVW YVXZFHV LU RMXIVZHVW EZIRVGB LU WRHVZHVH  GSV KLOOFGVW ZRI DV YIVZGSV VEVIB NLNVMG',

'XZFHRMT OFMTH WRHLIWVIH ZMW VEVM OFMT XZMXVI GSFH ZUUVXGRMT GSV SVZOGS LU LGSVI YLWB LITZMH  ZRI KLOOFGRLM RH XLMGRMFLFHOB WZNZTRMT GSV DSLOV VXLOLTRXZO HBHGVN ZMW ZUUVXGRMT GSV OREVH LU KOZMGH ZMW ZM',

'RNZOH ZH DVOO  RG SZH IVZXSVW GL GSV XIRGRXZO HGZTV ZMW ZUUVXGRMT GSV DSLOV ZGNLHKSVIV YB ZOOLDRMT NLIV SZINUFO IZWRZGRLMH UILN GSV HFM GL GSV VZIGS  ZTZRM KLOOFGVW ZRI ZXGH ZH Z YVGGVI RMHFOZGLI DSRXS',

'KIVEVMGH SVZG GL TVG VHXZKVW YZXP RMGL GSV HKZXV  ZRI KLOOFGRLM RH LMV LU GSV NZRM VMERILMNVMGZO RHHFVH MLDZWZBH  GSVIV ZIV NZMB IVZHLMH YVSRMW IVTFOZIOB RMXIVZHRMT GSRH ZRI KLOOFGRLM  NLHG LU GSV ZRI',

'KLOOFGRLM RH XZFHVW YB GSV ZFGLNLYROVH  GIZMHKLIG NVZMH  RMWFHGIRZORAZGRLM  TILDRMT XRGRVH  VGX  GSV IVOVZHV LU HVEVIZO SZINUFO TZHVH LI WZMTVILFH VOVNVMGH UILN HFXS HLFIXVH RH XZFHRMT GSV DSLOV ZGNLH',

'KSVIRX ZRI KLOOFGRLM  LALMV OZBVI RH ZOHL TVGGRMT ZUUVXGVW GLL NFXS YB GSV ZRI KLOOFGRLM DSRXS XZFHVH HVIRLFH WRHGFIYZMXVH GL GSV VMERILMNVMG  RMXIVZHRMT MVVW LU GSV VEVI TILDRMT SFNZM KLKFOZGRLM RH N',

'ZRM XZFHV LU KLOOFGRLM  WZROB SFNZM YVRMT ZXGRERGRVH XZFHRMT WZMTVILFH XSVNRXZOH GL IVOVZHV  NZPRMT ZGNLHKSVIV WRIGRVI GSZM VEVI ZMW ULIXRMT GSV XORNZGV XSZMTV MVTZGREVOB  RMWFHGIRZORAZGRLM KILXVHH IV',

'OVZHVH NZMB SZINUFO TZHVH  KZIGRXOVH  KZRMG ZMW YZGGVIRVH XLMGZRMH OVZW  XRTZIVGGVH IVOVZHVH XZIYLM NLMLCRWV  GIZMHKLIG NVZMH IVOVZHVH XL  ZMW LGSVI GLCRX HFYHGZMXVH GL GSV ZGNLHKSVIV  ZOO GSV KLOOFGZ',

'MGH ZIV YVRMT RM XLMGZXG DRGS GSV ZGNLHKSVIV  WVHGILBRMT GSV LALMV OZBVI ZMW XZOORMT SZINUFO IZBH LU HFM GL GSV VZIGS  RM LIWVI GL IVWFXV GSV OVEVO LU ZRI KLOOFGRLM DV HSLFOW YIRMT HLNV SFTV XSZMTVH G',

'L LFI SZYRGH LM WZROB YZHRH  DV HSLFOW MLG XFG GIVVH  FHV KFYORX GIZMHKLIGZGRLM  ZELRW HKIZB XZMH  ZMW HL NZMB ZXGRERGRVH RM GSV UZELI GL IVWFXV GSV VUUVXGH LU ZRI KLOOFGRLM  ZRI KLOOFGRLM RH GSV NRCR',

'MT LU ULIVRTM HFYHGZMXVH GL GSV DSLOV ZGNLHKSVIRX ZRI  SZINUFO ZMW GLCRX TZHVH VNRGGVW YB GSV RMWFHGIRVH ZMW NLGLI EVSRXOVH XZFHRMT SFTV WZNZTV GL GSV ORERMT LITZMRHNH DSVGSVI KOZMGH  ZMRNZOH LI SFNZM',

'YVRMTH  HLNV LU GSV MZGFIZO ZMW EZIRLFH SFNZM IVHLFIXVH ZIV XZFHRMT ZRI KLOOFGRLM  SLDVEVI  NLHG LU GSV ZRI KLOOFGRLM HLFIXVH ZIV HGVN LFG LU GSV SFNZM ZXGRERGRVH ORPV YFIMRMT ULHHRO UFVOH  XLZO ZMW L',

'LORO  IVOVZHV LU SZINUFO TZHVH ZMW HFYHGZMXVH UILN UZXGLIRVH ZMW NLGLI EVSRXOVH  HFXS SZINUFO XSVNRXZO XLNKLFMWH ORPV XZIYLM WRLCRWV  MRGILTVM LCRWVH  XZIYLM NLMLCRWV  HFOKSFI WRLCRWV  HLORW KZIGRXOVH',

'VGX ZIV TVGGRMT NRCVW GL GSV UIVHS ZRI  GSV OVEVO LU ZRI KLOOFGRLM SZH YVXLNV RMXIVZHVW YB TIVZG VCGVMG YVXZFHV LU    RMXIVZHV RM WZNZTRMT KLOOFGZMGH YVXZFHV LU GSV VCKZMWVW MVVW LU NLGLI EVSRXOVH UIL',

'N OZHG XVMGFIB LGSVI HLFIXV LU GSV ZRI KLOOFGRLM RH WVXLNKLHRGRLM LU TZIYZTV RM OZMWUROOH ZMW WRHKLHZO LU HLORW DZHGVH DSRXS ZIV VNRGGRMT NVGSZMV TZH  WZMTVILFH GL GSV SVZOGS   IZKRW TILDGS LU KLKFOZG',
'MRLM  RMWFHGIRZORAZGRLM  RMXIVZHVW FHV LU ZFGLNLYROVH  ZVILKOZMVH  VGX SZH NZWV GSRH RHHFV Z HVIRLFH VMERILMNVMGZO KILYOVN  GSV ZRI DV YIVZGSV VEVIB NLNVMG RH UFOO LU KLOOFGZMGH TLRMT GL LFI OFMTH ZMW',

'DSLOV YLWB GSILFTS YOLLW XZFHRMT FMXLFMGZYOV SVZOGS KILYOVNH  KLOOFGVW ZRI RH XZFHRMT WZNZTV GL GSV KOZMGH  ZMRNZOH ZMW SFNZM YVRMTH RM NZMB WRIVXG ZMW RMWRIVXG DZBH  RU GSV VMERILMNVMGZO KILGVXGRLM K',

'LORXRVH ZIV MLG ULOOLDVW HVIRLFHOB ZMW HGIRXGOB  GSV RMXIVZHRMT OVEVO LU ZRI KLOOFGRLM NZB RMXIVZHV FK GL LMV NROORLM GLMH ZMMFZOOB RM GSV IVXVMG WVXZWVH DSVM GSV UIVHS ZRI TVGH KLOOFGVW YB NVZMH LU W',

'FHG  GLCRX TZHVH  HNLPV  NLGLI EVSRXOVH  NROOH ZMW UZXGLIRVH  VGX XZOOVW ZRI KLOOFGRLM  ZH DV ZOO PMLD GSZG UIVHS ZRI RH GSV NLHG RNKLIGZMG VOVNVMG LU GSV SVZOGSB ORUV  DV MVVW GL GSRMP GSZG DSZG SZKK',

'VMH RU DSLOV ZGNLHKSVIRX ZRI TVGH WRIGB  URIHG LU ZOO ZRI KLOOFGRLM RH GSV NZGGVI LU TIVZG IVTIVG ULI GSV DSLOV SFNZM UIZGVIMRGB  HLNV LU GSV YRT IVZHLMH LU GSV ZRI KLOOFGRLM ZIV FHV LU KLRHLMLFH UVIG',

'RORAVIH  RMHVXGRXRWVH  KVHGRXRWVH RM GSV ZTIRXFOGFIZO HVXGLIH YB GSV RMMLXVMG UZINVIH RM LIWVI GL RMXIVZHV GSV XILK KILWFXGRLM  IVOVZHVW XSVNRXZOH ZMW SZAZIWLFH TZHVH  ZNNLMRZ  UILN HFXS UVIGRORAVIH Z',

'IV TVGGRMT NRCVW RMGL GSV UIVHS ZRI ZMW XZFHRMT ZRI KLOOFGRLM YFIMRMT LU ULHHRO UFVOH HFXS ZH XLZO  KVGILOVFN RMXOFWRMT LGSVI UZXGLIB XLNYFHGRYOVH ZIV GSV NZQLI XZFHVH LU ZRI KLOOFGRLM  EZIRVGB LU HNL',

'PV VNRHHRLMH UILN GSV ZFGLNLYROVH HFXS ZH XZIH  YFHVH  NLGLIXBXOVH  GIFXPH  QVVKH  GIZRMH  ZVILKOZMVH  VGX ZIV ZOHL XZFHRMT ZRI KLOOFGRLM  RMXIVZHRMT MFNYVI LU RMWFHGIRVH RH XZFHRMT IVOVZHV LU GLCRX R',

'MWFHGIRZO HNLPVH ZMW SZINUFO TZHVH  ORPV XZIYLM NLMLCRWV  LITZMRX XLNKLFMWH  SBWILXZIYLMH  XSVNRXZOH  VGX  UILN GSV UZXGLIRVH ZMW NROOH GL GSV VMERILMNVMG  HLNV RMWLLI ZXGRERGRVH LU GSV KVLKOV ORPV RM',

'MMLXVMG FHV LU XOVZMRMT KILWFXGH  DZHSRMT KLDWVIH  KZRMGH VGX VNRGH EZIRLFH GLCRX XSVNRXZOH GL GSV ZRI  GSV VEVI RMXIVZHRMT OVEVO LU ZRI KLOOFGRLM ZOHL VMSZMXVH RGH MVTZGREV ZMW SZINUFO VUUVXGH GL GSV',

'SVZOGS LU ORERMT YVRMTH  ZRI KLOOFGRLM RH XZFHRMT TOLYZO DZINRMT GL RMXIVZHV YVXZFHV LU RMXIVZHRMT ZGNLHKSVIRX GVNKVIZGFIV WFV GL GSV RMXIVZHRMT OVEVO LU TIVVM SLFHV TZHVH  HFXS TIVVM SLFHV TZHVH ZTZR',
'M XZFHRMT TIVVM SLFHV VUUVXG ZMW ULIXRMT HVZ OVEVOH GL RMXIVZHV  TOZXRVIH GL NVOG  DVZGSVI GL XSZMTV  XORNZGV GL XSZMTV  VGX  RMXIVZHRMT ZRI KLOOFGRLM RH XZFHRMT NZMB OVGSZO WRHVZHVH  XZMXVI  SVZIG ZG',

'GZXP  ZHGSNZ  YILMXSRGRH  PRWMVB WRHVZHVH  VGX  ZMW WVZGS GL LXXFI  EZIRLFH RNKLIGZMG ZMRNZOH ZMW KOZMGH HKVXRVH SZEV YVVM WVHGILBVW XLNKOVGVOB UILN GSRH KOZMVG  RMXIVZHRMT OVEVO LU SZINUFO TZHVH RM G',

'SV VMERILMNVMG ZIV XZFHRMT GSV LXXFIIVMXV LU ZXRW IZRM ZMW WVKOVGRMT GSV LALMV OZBVI  RMXIVZHRMT XLMXVMGIZGRLM LU GSV SZINUFO ZMW GLCRX NZGVIRZOH RM GSV UIVHS ZRI LU GSV ZGNLHKSVIV RH XZFHRMT ZRI KLOO',

'FGRLM  EZIRVGB LU ULIVRTM KZIGRXOVH  GLCRX TZHVH ZMW LGSVI KLOOFGZMGH IVOVZHVW UILN EZIRLFH SFNZM ZXGRERGRVH ZIV ZUUVXGRMT GSV UIVHS ZRI DSRXS SZH ZWEVIHV VUUVXG GL GSV ORERMT YVRMTH ORPV SFNZM YVRMTH',

'ZMRNZOH ZMW KOZMGH  GSV OVEVO LU ZRI KLOOFGRLM WVKVMWH LM GSV GBKV ZMW ZNLFMG LU KLOOFGZMGH IVOVZHVW UILN EZIRLFH HLFIXVH  GLKLTIZKSRXZO ZMW NVGVLILOLTRXZO XLMWRGRLMH ZIV RMXIVZHRMT GSV HKIVZW ZMW XLM',

'XVMGIZGRLM LU GSV KLOOFGZMGH  EZIRVGB LU IZD NZGVIRZOH FHVW RM GSV NZMFUZXGFIRMT KILXVHH RM RMWFHGIRVH RH RMXIVZHRMT GSV GBKV ZMW JFZMGFN LU VNRHHRLMH LU SZINUFO TZHVH  RMXIVZHRMT KLKFOZGRLM WVMHRGB R',

'H WVNZMWRMT GSV MVVW LU NLIV RMWFHGIRZORAZGRLM DSRXS FOGRNZGVOB XZFHVH ZRI KLOOFGRLM  ZRI KLOOFGZMGH ORPV SZINUFO ORJFRW WILKOVGH  HLORWH KZIGRXFOZGVH  ZMW GLCRX TZHVH ZMW ZRI HNLPV XZFHRMT HNLT ZMW S'
]

VG = ['ORRBMCC HSVC AYQNVIROH YXH DEPJI JGVPCN QSCX ZO WSLQGDXCN YQSRE DLC YRJSRC KTNVMAKXGYR QIWROQ ZOJMBI NW SL DL KKC EEMBOPGXIQ PSP DLC ORRBMCC XFO APSXC ET QRSSVH CSXFOV ZO WSLQGDXCN ML RMLNM MB ILQPGCL',
'GX GYCI QEFKSWQSSL SW GX ELI SRRIP VELQYYQI  GD QSCX ZO EAMSKZELSIB GMRR XPKRQVERSSL SR CSXFOV FSRBS SP OREVMQR MR MSSVH ZO EL SRBSZGNYYV TPYNCMX MB E ROEK ZVMTIAD  LMGITOV  GX GYCI MP XCKQ  RRI RYXYV',
'XCKQ KOQZOVQ  SRAVYBSRE DLC DIYW PCKHCB  WFYYJN RMD IVMICN WGH RM BIDOVCXGC YJ RRI GNILDMRI SD DLC ZIPCSL CYZWMRDMLQ WFYYJN FC WEBO ML DLC ZVMZSQKP  GP HMXI QY  MR CLYVP JOEB DS RRI CXXPI KCDXGXK PONC',
'MXCN MR SW QDVMXKJI EBFMQOH LYX RY AYSX RSPJ DLC MPMCYPO XGWI DYV QEFKSWQSSL YJ CXXPSIQ  BEGVAYIW QREJV RMD FC BIQZSLCMZVI DYV JKXC XSL BIAOMND SD ORRBMCC SL KGAYYLD SD CIPFIP OVPYVQ DVYPJGM XFO GMXXC',
'CXYXXQ WEW LI YCOCN XM ZVCCILD  IJKFMBERO XFOMP SHCKW ZOJMBI YX ENZVMZVGKXC TYPI VYSPUKCQ WEW NIASHC DS YCWMMMYDI USXF DLC ZVMZSQOV DYV DEVRRIP NITOPMZQCXX MP XFO TPYTMCIB MSLMIND MBOE RRI BOGGCMMX SD',
'DLC OZYVYYDMMX TYXIJ KRB TYPI AGVP ZO JGXEJ  XS AYQKERGMERSSL GMJV FC ORROVCN AGDL YXC NOVQYR GX VCVERSSL DS YXC BOGGCMMX SD DLC ZELOP MB TPYGCCW SXWSMGCCWDEP CXXPSIQ CLYVP ZO MLDMKKXCN XFBSSQL CWEGVE',

 'LN QGXMQDVW YJ PKMJGEWC WFKPJ XSR RETO ELI VGQLR YZCB XFO WYWI RRI AYQNOXGDMMX MQ YTCX XM SRBSZGNYYVW YXH AYQNKRGOW MB MLCXGDYRSSLC  XFO TYBXGMMNKRRC EPO VCAYGBIB DS ZO ER VIYCX WOEPC SD KKC  DLC OZYV',

 'YYDMMX SD DLC ORRBMCC AGVP ZO GYBVGOH MEX GX XFBIC CXYQIQ  SR RRI DSVQD WRKKC ORRBMCC AGVP ZO WFYVRVMQDIB KJROV CFEJEERSSL KRB DLC CLMBXJSWROH CXXPSIQ GMJV FC PYPDLCB ITKPSKXCN FW KR CHTCBX NKRCV SL C',

 'WCMSLN WRKKC PSP CIJOGRSSL WSQD TPYQGCMLQ MBOEQ  DLC PMLKP    GNIYC AGVP ZO TPOWCXXCN XM MSKZIRSXGYR AYQKSXROI URMAR MQ PSPWIB LC RRI KSRGCXPI JMB GMXWGNIPKXGYR MP EUKVBC  WM  GLYD EPO CME AYSXGXK DYV',

 'TSWGD XFO SDPMASEJ GIZCMRO SD TEL LLYQMBKVG DS NKVRSGGZERO ML DLGC GMWTCDMRSSL NEW LC BKC RRI DBIQR EGB SD DLC ORTSVMXQCXX GC KCDXGXK NYPJEXCN FCMESCI MP XFO QGHMLQ SD ZEPDMAEPYDIQ  LMMVSESGYV QMVIAEP',

 'CC  ELN SRRIP REPWJSV QYDIPSEJC  WSML NYPJEXCN EGB MQ MESCMLQ LCKPRR TPYFJOQQ  NMQOEQOW YXH BOERR  EGB TMVPSDMMX MQ YRC YJ RRI KYWR SQNYVRKRR ORTSVMXQCXXYV MQCYCC AFSGF BIOEMPOW RY FC XSRSGCN ELN WMVZ',
 'CN FW DLC OJDYVRC SD KPJ YJ SC  ML YVBOV RY MLMVCKWC KAYBILOWQ KQMXK QDYBORRC EZYYR DLGC MQCYC  KMP ZSJVYRSSL OWQKC FKW ZOGMWI YX MKZSPDELD XMZMA PSP DLC OWQKC UBMRSRE MSKZIRSXGYR  QY WREHCXXQ ISS KVC',

 'KX PSKFD TJKGC  TYQD KM KLCKH  QEGF OWQKC MX EGB TMVPSDMMX AGVP FOPN ISS DS USR CCWYI APSXGXK AYQNOXGDMMX FCMESCI YVP YBI UBMRDIL SR TOVW CMKZPC OREVMQR PYXKSKKC EWGXK CKWW GSPNW  YSV NYPJEXGYR GC E K',

 'YWR CIPSSSC TPYFJOQ MP XFO GSBVCXX RSQC KPJ YZCB XFO AMBPB OWNOGGKPJI ML DLC VEPQI ASXGOW ZOGYEWC YJ RRI FEKC VITOP MP MLNYQDVGKPGJERSSL  DLC BIJOEQO SD CYAR EGB TMVPSDELDW GX LCKZW MSLMILDVYDMMXW QE',

 'TYBXGMYJKXCC  WMVMB WEROVGKPQ  OXA KVC QIRDMLQ WCDXJOH MFIP DLC MMRI  GYEWGXK YSV NYPJEXGYR YXH FOEJDL FKDYBHQ DS RRI NOSNVI  JYXQ YJ BSVRI AYCXCC TPYHSMIB LC NOSNVI MX HYSPW LEQSW CCTCMMYVPW SR RRI Z',

 'SK ASXGOW NYPJEXGXK RRI URSJO ERWSQZLCBMA KMP DS Y QVCKX CHXCXX  YSV NYPJEXGYR GC XFO QGHMLQ SD KRW REPWJSV WSLWRKRAOW RY XFO ERWSQZLCBI DBIQR EGB GYEWGXK FEKC VITOP MP HYWEEOW  FEQYX LCKPRR HGCSPNIPC',

 'VCNYASRE DLC AYYVMRI SD VMDO  IRM  EGB TMVPSDMMX MQ SRABIYCMLQ HYI FW NEW LIAKYQO SD DLC SRABIYCMLQ RSWFCB SD SRBEWRBMCC  WSML NYPJEXCN EGB RCFIP BIKKMLC ER YRC ZPYMI FYACFIP CTPOEB DS URSJO ILFMPYRK',

 'WILD ELN EDPIADMLQ XFO PGFIQ YJ RRI NOSNVI YVP RRVMEKF DLC GSPVH  BOERR VYDIQ YJ RRI FEQYX FCSREC LYFI ZOIL SRABIYCIB LIAKYQO SD SRABIYCIB FEPSIRI SD NMQOEQOW  RRI NYPJEXCN EGB AC LVCKXFO ITOVW WSKORR',

 'MESCMLQ PSXKQ NMQYVBOVQ KRB OZCX PSXK AKRAOV RRYQ KJDOGRSRE DLC RIYVXF YJ MDLCB FMNC MBKYXW  YSV NYPJEXGYR GC GMXXGXYMEWJI HYWEESRE DLC GLMVI CMSJYKGMEJ CCQDIK KRB KJDOGRSRE DLC VMTOW MP TJKRRC ELN EL',

 'SQYVW YC ACVP  GD LYC VCKGFOH RY XFO GPSXGMEJ CXYQI YXH YPJCMXGXK RRI URSJO ERWSQZLCBI ZI EJVSUSRE WSPO LYBQDEP PKHGKXGYRQ PVMW XFO WSX XM DLC OEPDL  YQEGX TMVPSDIB KMP KGRC EQ K FCDXCB MLCYJKXMB AFSGF',

 'ZVCFILDW FOER DS EOX CCGYZIB LEAU MLDS RRI QZEAO  EGB TMVPSDMMX MQ YRC YJ RRI KKML ORTSVMXQCXXYV MQCYCC RMGEBKCQ  DLCBI YBI KKRW BIYCSLC FCRMLN VCQYJKVJI MLMVCKWGXK RRMQ KMP ZSJVYRSSL  WSQD SD DLC KMP',

 'ZSJVYRSSL SW AKYQOH ZI XFO ESDSKYFGVIQ  DVYXWNYVR WIYXW  GXHSCXPSEJSDYDMMX  KPYAGXK ASXGOW  CDG  RRI POPCKWC YJ QOZCBEJ REPWJSV KYCIQ YV BKREOVMEW CVIKORRC JPYQ QEGF CSSBGCC MQ MESCMLQ XFO AFYPC KXKYW',

 'NRIPSG YSV NYPJEXGYR  MJSLO PYIIP SW YVWM QIRDMLQ EDPIADIB DSM WYAR FW DLC KMP ZSJVYRSSL GLGML AKYQOW QOVGYYQ NMQDYPLELMIQ DS RRI CXZGBSLWILD  MLMVCKWGXK LOIB YJ RRI CFIP QVMGMLQ LSWEL ZSNEPYDMMX MQ W',

 'EGX GYEWC YJ NYPJEXGYR  BKMJI LSWEL LIGXK YMXGFMRSIQ MESCMLQ HYXKCBSSC GFOQGMEJC XM BIJOEQO  QYUMLQ ERWSQZLCBI BSVRSIP DLYX ITOV YXH DYVASRE DLC MPGWERO GFKREO RCQERSZCVC  GXHSCXPSEJSDYDMMX TPYGCCW PO',

 'PCKWCC QYXC FKVKPYJ QEQOW  NKVRSGJOW  NKMLD ELN FYDXCBMCC GMXXYSRQ VIYN  GGQEPOXROW POPCKWCC GYBFMX QMXSVSHC  DVYXWNYVR WIYXW POPCKWCC GM  KRB YXFOV RYBGM WSLWRKRAOW RY XFO ERWSQZLCBI  YVP RRI NYPJEXY',

 'XXQ KVC LIGXK GX GMXXYMX USXF DLC KXKYWNRIPO  HCCXPYCGXK RRI MJSLO PYIIP KRB MEJVMLQ LYBQDEP PKCQ YJ QER RY XFO IYBXF  SR MBHCB XM BIBEGC DLC VITOP MP EGB TMVPSDMMX AC CLMEPB LVGXK QYQC RYEO GFKREOW R',

 'Y SSB LYLMRC SL NEGVC ZKWGC  AC CLMEPB XSR MYR DVCOW  SCI NEFJSG RBELCTMBXYDMMX  ETYMB CTPKC AKRQ  KRB CS KKRW KGRSZGDMCC ML DLC PETYV RY VCNYAO XFO IDPIADW MP EGB TMVPSDMMX  EGB TMVPSDMMX MQ DLC WMVS',

 'RE YJ DYVCSKL CYZCXYXGCC XM DLC GLMVI YDQMCTFOVGM EGB  LYBQDEP YXH RYBGM KYCIQ OQGDXCN FW DLC SRBEWRBMCC ELN QMDSP FIFSGJOW AKYQSRE RYEO HYWEEO XM DLC VMTSRE YVEKRGCQQ GLCDLCB TJKRRC  ELSQYVW MB LSWEL',

 'LIGXKQ  CSKO SD DLC XEREVYV ELN ZYBMMEW FEQYX VCCSSBGCC EPO GYEWGXK YSV NYPJEXGYR  FYACFIP  WSQD SD DLC KMP ZSJVYRSSL CSSBGCC EPO WROQ MEX MP XFO LSWEL KGRSZGDMCC PGUI ZEVLSRE PSQCMJ PYCVW  AYEJ KRB Y',

 'SJSP  POPCKWC YJ FKVKPYJ QEQOW YXH QEFQDELMIQ PVMW JYMXMBMCC ELN QMDSP FIFSGJOW  QEGF REPWJSV GFOQGMEJ MSKZSSXHQ VMIO GYBFMX HGYBGNI  LSXPYKCX SVSHCC  GYBFMX QMXSVSHC  CYJZLSB HGYBGNI  QYPGN TYBXGMPCC',

 'IRM EPO KCDXGXK KSBCN XM DLC PVCCL YSV  RRI JOZCV SD KMP ZSJVYRSSL REQ LIAYQC SRABIYCIB LC EBIYD IVDILD FCMESCI MP    MLMVCKWC SR BKQYQMLQ TMVPSDELDW ZOGYEWC YJ RRI CHTYXHCN RCOH MP QMDSP FIFSGJOW DBS',

 'K VEQD GCXXSBC MDLCB WMEVAO SD DLC KMP ZSJVYRSSL SW BOGMWTMCMRSSL YJ EKVZKKC SR JKRBPMJVW YXH BSWNYWYV SD CSJSH UKWROW URMAR EPO IKSXRSRE WIRRELO KYC  HYXKCBSSC XM DLC RIYVXF   BENSH EBSUDL MP TMZYJKX',
 'LSSL  SRBEWRBMYVMXKXGYR  GXGPOEQOH SCI MP ESDSKYFGVIQ  KIPYTJKRCC  IRM LYC QYNI RRMQ SWQEI Y CIPSSSC ILFMPYRKORRKP NBSZVIK  DLC KMP GI ZBIYDLC OZCBC KYQCXX GC JSVP MP TMVPSDELDW EYMLQ XM YYP VYLQW YXH',

 'URSJO FMNC RRVMEKF LPMYH AKYQSRE ERAYYLDEZVI FOEJDL NBSZVIKC  TMVPSDIB KMP SW AKYQSRE NEKKKC DS RRI NVELDW  YXMKKPQ KRB RYKKR ZOMLQW GX QYXC BSVCMX YXH GXHGBIAD AYIW  GP XFO ILFMPYRKORRKP NBSROGRSSL Z',

 'SJSGGOW YBI LYX DYPJYACN WCBMMEWJI ELN WRBMADPW  DLC SRABIYCMLQ PCFIJ YJ YSV NYPJEXGYR KKC GXGPOEQO YN DS MXI KSPJSSL DSLC ELXYYVPW SR RRI POGCXX BOGYNIQ GLCX XFO JPOWF KMP QIRC TMVPSDIB LC KOELC SD N',

 'YQD  XMHMA QEQOW  QWSIO  QMDSP FIFSGJOW  KSPJC ELN JYMXMBMCC  IRM GYVPCN EGB TMVPSDMMX  EQ GI YVP IXSU DLYD JPOWF KMP SW RRI KYWR SQNYVRKRR OPCWILD SD DLC RIYVXFI PGPI  UO RCOH RY XFSRI DLYD AFKX FKTN',

 'ORQ SJ URSJO ERWSQZLCBMA KMP QIRC HGBXW  PMPCX MP EJV EGB TMVPSDMMX MQ DLC WERDIP YJ EBIYD VCQVCD JMB XFO AFYPC RYKKR DBEROVLSXW  CSKO SD DLC LME BIYCSLC SD DLC KMP ZSJVYRSSL KVC EWC YJ NYMQYRMEW DOVR',

 'SPGJIPC  MLCIADMASHCC  TCCXGMMBOW GX XFO EEBMAEPREVYV WCMXMBW ZI XFO MLXSAORR PEPWIPC ML YVBOV RY MLMVCKWC DLC MVMZ TPYHSMXGYR  POPCKWCN GFOQGMEJC ELN LYJEPNSSC KYCIQ  KQKYRGK  JPYQ QEGF PIPDMJSDCBW Y',

 'BI EOXRSRE WMVOH GXXM DLC PVCCL YSV YXH AKYQSRE KMP ZSJVYRSSL LYPXMLQ SD PSQCMJ PYCVW QEGF KW AYEJ  ZIRBSJOYK SRAVYBSRE YXFOV DKGRYVW MSKLYQDMZVIQ KVC DLC WEHYV AKYQOW MP EGB TMVPSDMMX  ZYBMCDC MP WKY',

 'OC OQGCWGYRQ PVMW XFO ESDSKYFGVIQ CYAR EQ MEPC  FSCIQ  WSRYVAIGJOW  RBYAUW  HOINC  XPKMLC  ECBSNVELOW  CDG YBI YVWM MESCMLQ EGB TMVPSDMMX  MLMVCKWGXK LEQZOV MP MLNYQDVGOW GC GYEWGXK POPCKWC YJ RYBGM M',

 'LNYQDVGKP QWSIOW YXH FKVKPYJ QEQOW  JSOC MEPLSL WSLYBGNI  MBKYXMA MSKZSSXHQ  RCBBSAKVZYRQ  MLCWMAKPQ  OXA  PVMW XFO JYMXMBMCC ELN QGVPQ DS RRI CXZGBSLWILD  WMWI GXHMYV YMXGFMRSIQ YJ RRI NOSNVI JSOC SR',

 'LXSAORR EWC YJ AVIYXMLQ TPYHSMXQ  GEQRMLQ TMGHCBW  NKMLDW CDG CWMRC ZYBMMEW RYBGM GFOQGMEJC XM DLC KMP  DLC OZCB MLMVCKWGXK JOZCV SD KMP ZSJVYRSSL KPQY ILRELMIQ SXQ XIEKXGFI YXH FKVKPYJ OJDOGRC XM DLC',

 'RIYVXF YJ JSZGXK ZOMLQW  YSV NYPJEXGYR GC GYEWGXK EVSZKP UKVKSRE DS GXGPOEQO FCMESCI MP MLMVCKWGXK YDQMCTFOVGM XCWTCBEREVC NYC DS RRI GXGPOEQSRE VITOP MP KPOIL RSSCI EKWCC  WSML EBICX LMEWC QEQOW YQEG',
 'X GYEWGXK EBICX LMEWC OJDOGR KRB PSPMMLQ WCK PCFIJC XM SRABIYCI  EVEASIPC XM WIJD  ACKXFOV RY GFKREO  GJSQYDI RY GFKREO  IRM  MLMVCKWGXK YSV NYPJEXGYR GC GYEWGXK KKRW VIRREJ NMQOEQOW  AKRAOV  FOEPD ER',

 'DEAU  EQDLKK  FPYRARMRSW  ISHLOC BSWCKWCC  IRM  ELN HCKXF DS MMGSB  ZYBMMEW GWTMBXYXX YXMKKPQ KRB ZPYXXQ CTCMMCC LYFI ZOIL NIQDVMIIB MSKZPCDIJI JPYQ RRMQ ZPYXIR  SRABIYCMLQ PCFIJ YJ FKVKPYJ QEQOW GX X',

 'FO ILFMPYRKORR KVC MESCMLQ XFO SAMYPBILMI MP EASH PKML KRB NINVIRSRE DLC YDMXI JKCCB  MLMVCKWGXK AYRAORRBERSSL YJ RRI FKVKPYJ KRB DSVSG KKXCBMYVW GX XFO JPOWF KMP YJ RRI YDQMCTFOVC SW AKYQSRE KMP ZSJV',

 'YRSSL  FEPSIRI SD PSPOMEX TYBXGMPCC  XMHMA QEQOW YXH MDLCB TMVPSDELDW POPCKWCN JPYQ TKVGYYQ RYKKR YMXGFMRSIQ KVC KJDOGRSRE DLC PVCCL YSV URMAR LYC EBFIPCI CPJCMX RY XFO PGFMLQ FCSREC PGUI FEQYX FCSREC',

 'ELSQYVW YXH NVELDW  RRI JOZCV SD KMP ZSJVYRSSL NINORBC SL DLC DCNO ELN EKYYLD SD ZSJVYRKRRC VCVIYCIB PVMW ZYBMMEW QYYPMIQ  DSNYKPKTFSGYV ELN QCDIMBSJYKGMEJ MSLNMRSSLC EPO MLMVCKWGXK RRI QZVCKH YXH AYR',

 'AORRBERSSL YJ RRI NYPJEXYXXQ  FEPSIRI SD BEU WEROVGKPQ EWCN ML DLC WELEJYMXSBMLQ TPYGCCW GX MLNYQDVGOW GC MLMVCKWGXK RRI RITC KRB AYYXXSW SD OQGCWGYRQ YJ FKVKPYJ QEQOW  GXGPOEQSRE ZSNEPYDMMX HCXWGDC G',

 'C HCWELNMLQ XFO RCOH MP QMBI GXHSCXPSEJSDYDMMX AFSGF EPRSQYDIJI GYEWCC EGB TMVPSDMMX  EGB TMVPSDELDW JSOC REPWJSV PGAYGN HPYTJOXQ  CSJSHQ ZEPDMAEPYDIQ  KRB DSVSG EKWCC ELN EGB WKYOC MESCMLQ WKYK YXH F'
]
Data_set = ['VMGIRVH WFOB XLNKOVGVW ZMW UFOOB UROOVW NFHG YV HFYNRGGVW FHRMT GSV LMORMV ZKKORXZGRLM HBHGVN YVULIV KN LM GS NZB TFRWVORMVH ULI GSV VMGIRVH GSV DIRGV FK HSLFOW VRGSVI YV HFYNRGGVW RM SRMWR LI VMTORHS',

'RM XZHV HFYNRHHRLM RH RM ZMB LGSVI OZMTFZTV  RG NFHG YV ZXXLNKZMRVW DRGS GIZMHOZGRLM RM VRGSVI SRMWR LI VMTORHS RG XLFOW YV ZM RMWRERWFZO KILQVXG LI Z GVZN KILQVXG  SLDVEVI  RM XZHV LU GVZN  GSV GLGZO',

'GVZN NVNYVIH  RMXOFWRMT GSV GVZN OVZWVI  HSLFOW MLG VCXVVW HRC ML IVUVIVMXV LU GSV RWVMGRGB LU GSV KVIHLM HFYNRGGRMT HSLFOW YV NZWV RM GSV KILKLHZO  RU WLMV HL  RG HSZOO OVZW GL GSV VMGIB TVGGRMT IVQV',

'XGVW RG RH HGILMTOB ZWERHVW MLG GL DZRG GROO GSV XOLHFIV GRNV ULI HFYNRHHRLM LU VMGIRVH  IZRODZBH HSZOO MLG YV IVHKLMHRYOV ULI OZGV MLM IVXVRKG LU VMGIRVH LM ZXXLFMG LU HVIEVI VIILIH GIZUURX GSV XLMGV',

'HGZMGH NZB YV ZHPVW GL KIVHVMG  VOZYLIZGV GSVRI RWVZH YVULIV ZM ZKKILKIRZGV QFIB IZRODZBH NZB WVXRWV GL ZHHLXRZGV DRGS GSV KILKLHVI ULI UFIGSVI WVEVOLKNVMG LU GSV KILKLHVW XLMXVKG RWVZ GSV WVXRHRLM LU',

'GSV VEZOFZGRLM KZMVO ZMW QFIB DROO YV URMZO  ML XLNNFMRXZGRLM DROO YV VMGVIVW DRGS ZMB KVIHLM RM IVOZGRLM GL ZMB WVXRHRLM LU GSV KZMVO LI KILXVHH FMHFXXVHHUFO VMGIRVH HSZOO YV RMGRNZGVW GSILFTS VNZROZ',

'MW NRMRHGIB LU IZRODZBH HSZOO MLG SZEV ZMB IRTSG LEVI GSV HZNV GSV XLNKVGRGRLM RH LKVM GL RMWRERWFZOH ZMW XLNKZMRVH LI RMHGRGFGRLMH  GSV KZIGRXRKZMGH ZIV IVJFRIVW GL YV ZG OVZHG BVZIH LU ZTV  GSV VEZO',

'FZGRLM LU GSV VMGIRVH DROO YV XZIIRVW LFG RM GSIVV HGZTVH  RM GSV URIHG HGZTV VMGIRVH DROO YV HSLIGORHGVW ZUGVI VEZOFZGRLM ZMW GSV HSLIGORHGVW VMGIRVH DROO YV UFIGSVI VEZOFZGVW YB ZM VCKVIG KZMVO LM H',

'HVXLMW HGZTV ULI HVOVXGRLM NLHG KILNRHRMT RWVZH  GSV URMZO    RWVZH DROO YV KIVHVMGVW GL XLNKVGRGRLM XLNNRGGVV DSRXS RH ULINVW YB GSV NRMRHGIB ULI XLMHRWVIZGRLM LU ZDZIWH  HL  DSZG ZIV BLF DZRGRMT ULI',

'ERHRG GSV LUURXRZO DVYHRGV LU QZM YSZTRWZIR GL KZIGRXRKZGV RM GSRH XLNKVGRGRLM WZB YB WZB GSV UIVHS ZRI LU GSV VMERILMNVMG RH TVGGRMT KLOOFGVW YVXZFHV LU GSV NRCRMT LU KZIGRXFOZGVH  YRLOLTRXZO NLOVXFO',

'VH  ZMW LGSVI SZINUFO NZGVIRZOH  HFXS KLOOFGVW ZRI RH XZFHRMT SVZOGS KILYOVNH  WRHVZHVH ZMW WVZGS  ZRI KLOOFGRLM RH LMV LU GSV NLHG RNKLIGZMG VMERILMNVMGZO RHHFVH DSRXS IVJFRIVH GL YV MLGRXVW ZMW HLOE',
'VW YB GSV VUULIGH LU ZOO LU FH  RM LIWVI GL RMXIVZHV ZDZIVMVHH ZNLMT HGFWVMGH ZYLFG GSRH RHHFV  ZRI KLOOFGRLM VHHZB SZH YVXLNV ZM RNKLIGZMG GLKRX ULI GSV VHHZB DIRGRMT XLNKVGRGRLM  HL HGFWVMGH BLF ZIV',

'ZG IRTSG KOZXV  QFHG TL ZSVZW  HFXS VHHZB LM ZRI KLOOFGRLM DROO SVOK BLF GL DRM VHHZB DIRGRMT XLNKVGRGRLM YVXZFHV ZOO ZIV DIRGGVM RM EVIB HRNKOV VMTORHS OZMTFZTV FHRMT VZHB DLIWH  ZRI KLOOFGRLM RH Z N',

'LHG HVIRLFH KILYOVN LU GSV XFIIVMG GRNV ZOO LEVI GSV DLIOW VHKVXRZOOB RM GSV OZITV XRGRVH YVXZFHV LU GSV SFTV OVEVO LU RMWFHGIRZORAZGRLM  GSV IVOVZHV LU HFXS ZRI KLOOFGZMGH RM SVZEB XLMXVMGIZGRLMH HF',

'KZIGRXFOZGVH  HLORW NZGVIRZOH  VGX ZIV TVGGRMT HVGGOVW LEVI GSV XRGB  XZFHRMT ZRI KLOOFGRLM ZMW SVZOGS SZAZIWH GL GSV KVLKOV  OLGH LU WRIGB DZHGVH KILWFXVW YB KVLKOV LM WZROB YZHRH VHKVXRZOOB RM GSV Y',

'RT XRGRVH KLOOFGRMT GSV DSLOV ZGNLHKSVIRX ZRI GL Z TIVZG VCGVMG  ZRI KLOOFGRLM RH GSV NRCRMT LU ZMB SZINUFO HFYHGZMXVH GL GSV ZGNLHKSVIV UIVHS ZRI XZFHRMT SFTV OVEVO LU WZNZTVH  SFNZM SVZOGS WRHLIWVIH',

'IVWFXRMT GSV JFZORGB LU ORUV  VGX  ZRI KLOOFGRLM RH RMXIVZHRMT WZB YB WZB YVXZFHV LU GSV RMXIVZHRMT MFNYVI LU RMWFHGIRVH  HFXS KLOOFGVW ZRI MVEVI IVNZRMH ZG LMV KOZXV SLDVEVI HKIVZW GL DSLOV VMERILMN',

'NVMG ZMW ZUUVXGRMT GSV OREVH LU GSV KVLKOV ZOO GSILFTS GSV DLIOW  WVZGS IZGVH LU GSV SFNZM YVRMTH SZEV YVVM RMXIVZHVW YVXZFHV LU RMXIVZHVW EZIRVGB LU WRHVZHVH  GSV KLOOFGVW ZRI DV YIVZGSV VEVIB NLNVMG',

'XZFHRMT OFMTH WRHLIWVIH ZMW VEVM OFMT XZMXVI GSFH ZUUVXGRMT GSV SVZOGS LU LGSVI YLWB LITZMH  ZRI KLOOFGRLM RH XLMGRMFLFHOB WZNZTRMT GSV DSLOV VXLOLTRXZO HBHGVN ZMW ZUUVXGRMT GSV OREVH LU KOZMGH ZMW ZM',

'RNZOH ZH DVOO  RG SZH IVZXSVW GL GSV XIRGRXZO HGZTV ZMW ZUUVXGRMT GSV DSLOV ZGNLHKSVIV YB ZOOLDRMT NLIV SZINUFO IZWRZGRLMH UILN GSV HFM GL GSV VZIGS  ZTZRM KLOOFGVW ZRI ZXGH ZH Z YVGGVI RMHFOZGLI DSRXS',

'KIVEVMGH SVZG GL TVG VHXZKVW YZXP RMGL GSV HKZXV  ZRI KLOOFGRLM RH LMV LU GSV NZRM VMERILMNVMGZO RHHFVH MLDZWZBH  GSVIV ZIV NZMB IVZHLMH YVSRMW IVTFOZIOB RMXIVZHRMT GSRH ZRI KLOOFGRLM  NLHG LU GSV ZRI',

'KLOOFGRLM RH XZFHVW YB GSV ZFGLNLYROVH  GIZMHKLIG NVZMH  RMWFHGIRZORAZGRLM  TILDRMT XRGRVH  VGX  GSV IVOVZHV LU HVEVIZO SZINUFO TZHVH LI WZMTVILFH VOVNVMGH UILN HFXS HLFIXVH RH XZFHRMT GSV DSLOV ZGNLH',

'KSVIRX ZRI KLOOFGRLM  LALMV OZBVI RH ZOHL TVGGRMT ZUUVXGVW GLL NFXS YB GSV ZRI KLOOFGRLM DSRXS XZFHVH HVIRLFH WRHGFIYZMXVH GL GSV VMERILMNVMG  RMXIVZHRMT MVVW LU GSV VEVI TILDRMT SFNZM KLKFOZGRLM RH N',

'ZRM XZFHV LU KLOOFGRLM  WZROB SFNZM YVRMT ZXGRERGRVH XZFHRMT WZMTVILFH XSVNRXZOH GL IVOVZHV  NZPRMT ZGNLHKSVIV WRIGRVI GSZM VEVI ZMW ULIXRMT GSV XORNZGV XSZMTV MVTZGREVOB  RMWFHGIRZORAZGRLM KILXVHH IV',

'OVZHVH NZMB SZINUFO TZHVH  KZIGRXOVH  KZRMG ZMW YZGGVIRVH XLMGZRMH OVZW  XRTZIVGGVH IVOVZHVH XZIYLM NLMLCRWV  GIZMHKLIG NVZMH IVOVZHVH XL  ZMW LGSVI GLCRX HFYHGZMXVH GL GSV ZGNLHKSVIV  ZOO GSV KLOOFGZ',

'MGH ZIV YVRMT RM XLMGZXG DRGS GSV ZGNLHKSVIV  WVHGILBRMT GSV LALMV OZBVI ZMW XZOORMT SZINUFO IZBH LU HFM GL GSV VZIGS  RM LIWVI GL IVWFXV GSV OVEVO LU ZRI KLOOFGRLM DV HSLFOW YIRMT HLNV SFTV XSZMTVH G',

'L LFI SZYRGH LM WZROB YZHRH  DV HSLFOW MLG XFG GIVVH  FHV KFYORX GIZMHKLIGZGRLM  ZELRW HKIZB XZMH  ZMW HL NZMB ZXGRERGRVH RM GSV UZELI GL IVWFXV GSV VUUVXGH LU ZRI KLOOFGRLM  ZRI KLOOFGRLM RH GSV NRCR',

'MT LU ULIVRTM HFYHGZMXVH GL GSV DSLOV ZGNLHKSVIRX ZRI  SZINUFO ZMW GLCRX TZHVH VNRGGVW YB GSV RMWFHGIRVH ZMW NLGLI EVSRXOVH XZFHRMT SFTV WZNZTV GL GSV ORERMT LITZMRHNH DSVGSVI KOZMGH  ZMRNZOH LI SFNZM',

'YVRMTH  HLNV LU GSV MZGFIZO ZMW EZIRLFH SFNZM IVHLFIXVH ZIV XZFHRMT ZRI KLOOFGRLM  SLDVEVI  NLHG LU GSV ZRI KLOOFGRLM HLFIXVH ZIV HGVN LFG LU GSV SFNZM ZXGRERGRVH ORPV YFIMRMT ULHHRO UFVOH  XLZO ZMW L',

'LORO  IVOVZHV LU SZINUFO TZHVH ZMW HFYHGZMXVH UILN UZXGLIRVH ZMW NLGLI EVSRXOVH  HFXS SZINUFO XSVNRXZO XLNKLFMWH ORPV XZIYLM WRLCRWV  MRGILTVM LCRWVH  XZIYLM NLMLCRWV  HFOKSFI WRLCRWV  HLORW KZIGRXOVH',

'VGX ZIV TVGGRMT NRCVW GL GSV UIVHS ZRI  GSV OVEVO LU ZRI KLOOFGRLM SZH YVXLNV RMXIVZHVW YB TIVZG VCGVMG YVXZFHV LU    RMXIVZHV RM WZNZTRMT KLOOFGZMGH YVXZFHV LU GSV VCKZMWVW MVVW LU NLGLI EVSRXOVH UIL',

'N OZHG XVMGFIB LGSVI HLFIXV LU GSV ZRI KLOOFGRLM RH WVXLNKLHRGRLM LU TZIYZTV RM OZMWUROOH ZMW WRHKLHZO LU HLORW DZHGVH DSRXS ZIV VNRGGRMT NVGSZMV TZH  WZMTVILFH GL GSV SVZOGS   IZKRW TILDGS LU KLKFOZG',
'MRLM  RMWFHGIRZORAZGRLM  RMXIVZHVW FHV LU ZFGLNLYROVH  ZVILKOZMVH  VGX SZH NZWV GSRH RHHFV Z HVIRLFH VMERILMNVMGZO KILYOVN  GSV ZRI DV YIVZGSV VEVIB NLNVMG RH UFOO LU KLOOFGZMGH TLRMT GL LFI OFMTH ZMW',

'DSLOV YLWB GSILFTS YOLLW XZFHRMT FMXLFMGZYOV SVZOGS KILYOVNH  KLOOFGVW ZRI RH XZFHRMT WZNZTV GL GSV KOZMGH  ZMRNZOH ZMW SFNZM YVRMTH RM NZMB WRIVXG ZMW RMWRIVXG DZBH  RU GSV VMERILMNVMGZO KILGVXGRLM K',

'LORXRVH ZIV MLG ULOOLDVW HVIRLFHOB ZMW HGIRXGOB  GSV RMXIVZHRMT OVEVO LU ZRI KLOOFGRLM NZB RMXIVZHV FK GL LMV NROORLM GLMH ZMMFZOOB RM GSV IVXVMG WVXZWVH DSVM GSV UIVHS ZRI TVGH KLOOFGVW YB NVZMH LU W',

'FHG  GLCRX TZHVH  HNLPV  NLGLI EVSRXOVH  NROOH ZMW UZXGLIRVH  VGX XZOOVW ZRI KLOOFGRLM  ZH DV ZOO PMLD GSZG UIVHS ZRI RH GSV NLHG RNKLIGZMG VOVNVMG LU GSV SVZOGSB ORUV  DV MVVW GL GSRMP GSZG DSZG SZKK',

'VMH RU DSLOV ZGNLHKSVIRX ZRI TVGH WRIGB  URIHG LU ZOO ZRI KLOOFGRLM RH GSV NZGGVI LU TIVZG IVTIVG ULI GSV DSLOV SFNZM UIZGVIMRGB  HLNV LU GSV YRT IVZHLMH LU GSV ZRI KLOOFGRLM ZIV FHV LU KLRHLMLFH UVIG',

'RORAVIH  RMHVXGRXRWVH  KVHGRXRWVH RM GSV ZTIRXFOGFIZO HVXGLIH YB GSV RMMLXVMG UZINVIH RM LIWVI GL RMXIVZHV GSV XILK KILWFXGRLM  IVOVZHVW XSVNRXZOH ZMW SZAZIWLFH TZHVH  ZNNLMRZ  UILN HFXS UVIGRORAVIH Z',

'IV TVGGRMT NRCVW RMGL GSV UIVHS ZRI ZMW XZFHRMT ZRI KLOOFGRLM YFIMRMT LU ULHHRO UFVOH HFXS ZH XLZO  KVGILOVFN RMXOFWRMT LGSVI UZXGLIB XLNYFHGRYOVH ZIV GSV NZQLI XZFHVH LU ZRI KLOOFGRLM  EZIRVGB LU HNL',

'PV VNRHHRLMH UILN GSV ZFGLNLYROVH HFXS ZH XZIH  YFHVH  NLGLIXBXOVH  GIFXPH  QVVKH  GIZRMH  ZVILKOZMVH  VGX ZIV ZOHL XZFHRMT ZRI KLOOFGRLM  RMXIVZHRMT MFNYVI LU RMWFHGIRVH RH XZFHRMT IVOVZHV LU GLCRX R',

'MWFHGIRZO HNLPVH ZMW SZINUFO TZHVH  ORPV XZIYLM NLMLCRWV  LITZMRX XLNKLFMWH  SBWILXZIYLMH  XSVNRXZOH  VGX  UILN GSV UZXGLIRVH ZMW NROOH GL GSV VMERILMNVMG  HLNV RMWLLI ZXGRERGRVH LU GSV KVLKOV ORPV RM',

'MMLXVMG FHV LU XOVZMRMT KILWFXGH  DZHSRMT KLDWVIH  KZRMGH VGX VNRGH EZIRLFH GLCRX XSVNRXZOH GL GSV ZRI  GSV VEVI RMXIVZHRMT OVEVO LU ZRI KLOOFGRLM ZOHL VMSZMXVH RGH MVTZGREV ZMW SZINUFO VUUVXGH GL GSV',

'SVZOGS LU ORERMT YVRMTH  ZRI KLOOFGRLM RH XZFHRMT TOLYZO DZINRMT GL RMXIVZHV YVXZFHV LU RMXIVZHRMT ZGNLHKSVIRX GVNKVIZGFIV WFV GL GSV RMXIVZHRMT OVEVO LU TIVVM SLFHV TZHVH  HFXS TIVVM SLFHV TZHVH ZTZR',
'M XZFHRMT TIVVM SLFHV VUUVXG ZMW ULIXRMT HVZ OVEVOH GL RMXIVZHV  TOZXRVIH GL NVOG  DVZGSVI GL XSZMTV  XORNZGV GL XSZMTV  VGX  RMXIVZHRMT ZRI KLOOFGRLM RH XZFHRMT NZMB OVGSZO WRHVZHVH  XZMXVI  SVZIG ZG',

'GZXP  ZHGSNZ  YILMXSRGRH  PRWMVB WRHVZHVH  VGX  ZMW WVZGS GL LXXFI  EZIRLFH RNKLIGZMG ZMRNZOH ZMW KOZMGH HKVXRVH SZEV YVVM WVHGILBVW XLNKOVGVOB UILN GSRH KOZMVG  RMXIVZHRMT OVEVO LU SZINUFO TZHVH RM G',

'SV VMERILMNVMG ZIV XZFHRMT GSV LXXFIIVMXV LU ZXRW IZRM ZMW WVKOVGRMT GSV LALMV OZBVI  RMXIVZHRMT XLMXVMGIZGRLM LU GSV SZINUFO ZMW GLCRX NZGVIRZOH RM GSV UIVHS ZRI LU GSV ZGNLHKSVIV RH XZFHRMT ZRI KLOO',

'FGRLM  EZIRVGB LU ULIVRTM KZIGRXOVH  GLCRX TZHVH ZMW LGSVI KLOOFGZMGH IVOVZHVW UILN EZIRLFH SFNZM ZXGRERGRVH ZIV ZUUVXGRMT GSV UIVHS ZRI DSRXS SZH ZWEVIHV VUUVXG GL GSV ORERMT YVRMTH ORPV SFNZM YVRMTH',

'ZMRNZOH ZMW KOZMGH  GSV OVEVO LU ZRI KLOOFGRLM WVKVMWH LM GSV GBKV ZMW ZNLFMG LU KLOOFGZMGH IVOVZHVW UILN EZIRLFH HLFIXVH  GLKLTIZKSRXZO ZMW NVGVLILOLTRXZO XLMWRGRLMH ZIV RMXIVZHRMT GSV HKIVZW ZMW XLM',

'XVMGIZGRLM LU GSV KLOOFGZMGH  EZIRVGB LU IZD NZGVIRZOH FHVW RM GSV NZMFUZXGFIRMT KILXVHH RM RMWFHGIRVH RH RMXIVZHRMT GSV GBKV ZMW JFZMGFN LU VNRHHRLMH LU SZINUFO TZHVH  RMXIVZHRMT KLKFOZGRLM WVMHRGB R',

'H WVNZMWRMT GSV MVVW LU NLIV RMWFHGIRZORAZGRLM DSRXS FOGRNZGVOB XZFHVH ZRI KLOOFGRLM  ZRI KLOOFGZMGH ORPV SZINUFO ORJFRW WILKOVGH  HLORWH KZIGRXFOZGVH  ZMW GLCRX TZHVH ZMW ZRI HNLPV XZFHRMT HNLT ZMW S',
'ORRBMCC HSVC AYQNVIROH YXH DEPJI JGVPCN QSCX ZO WSLQGDXCN YQSRE DLC YRJSRC KTNVMAKXGYR QIWROQ ZOJMBI NW SL DL KKC EEMBOPGXIQ PSP DLC ORRBMCC XFO APSXC ET QRSSVH CSXFOV ZO WSLQGDXCN ML RMLNM MB ILQPGCL',
'GX GYCI QEFKSWQSSL SW GX ELI SRRIP VELQYYQI  GD QSCX ZO EAMSKZELSIB GMRR XPKRQVERSSL SR CSXFOV FSRBS SP OREVMQR MR MSSVH ZO EL SRBSZGNYYV TPYNCMX MB E ROEK ZVMTIAD  LMGITOV  GX GYCI MP XCKQ  RRI RYXYV',
'XCKQ KOQZOVQ  SRAVYBSRE DLC DIYW PCKHCB  WFYYJN RMD IVMICN WGH RM BIDOVCXGC YJ RRI GNILDMRI SD DLC ZIPCSL CYZWMRDMLQ WFYYJN FC WEBO ML DLC ZVMZSQKP  GP HMXI QY  MR CLYVP JOEB DS RRI CXXPI KCDXGXK PONC',
'MXCN MR SW QDVMXKJI EBFMQOH LYX RY AYSX RSPJ DLC MPMCYPO XGWI DYV QEFKSWQSSL YJ CXXPSIQ  BEGVAYIW QREJV RMD FC BIQZSLCMZVI DYV JKXC XSL BIAOMND SD ORRBMCC SL KGAYYLD SD CIPFIP OVPYVQ DVYPJGM XFO GMXXC',
'CXYXXQ WEW LI YCOCN XM ZVCCILD  IJKFMBERO XFOMP SHCKW ZOJMBI YX ENZVMZVGKXC TYPI VYSPUKCQ WEW NIASHC DS YCWMMMYDI USXF DLC ZVMZSQOV DYV DEVRRIP NITOPMZQCXX MP XFO TPYTMCIB MSLMIND MBOE RRI BOGGCMMX SD',
'DLC OZYVYYDMMX TYXIJ KRB TYPI AGVP ZO JGXEJ  XS AYQKERGMERSSL GMJV FC ORROVCN AGDL YXC NOVQYR GX VCVERSSL DS YXC BOGGCMMX SD DLC ZELOP MB TPYGCCW SXWSMGCCWDEP CXXPSIQ CLYVP ZO MLDMKKXCN XFBSSQL CWEGVE',

 'LN QGXMQDVW YJ PKMJGEWC WFKPJ XSR RETO ELI VGQLR YZCB XFO WYWI RRI AYQNOXGDMMX MQ YTCX XM SRBSZGNYYVW YXH AYQNKRGOW MB MLCXGDYRSSLC  XFO TYBXGMMNKRRC EPO VCAYGBIB DS ZO ER VIYCX WOEPC SD KKC  DLC OZYV',

 'YYDMMX SD DLC ORRBMCC AGVP ZO GYBVGOH MEX GX XFBIC CXYQIQ  SR RRI DSVQD WRKKC ORRBMCC AGVP ZO WFYVRVMQDIB KJROV CFEJEERSSL KRB DLC CLMBXJSWROH CXXPSIQ GMJV FC PYPDLCB ITKPSKXCN FW KR CHTCBX NKRCV SL C',

 'WCMSLN WRKKC PSP CIJOGRSSL WSQD TPYQGCMLQ MBOEQ  DLC PMLKP    GNIYC AGVP ZO TPOWCXXCN XM MSKZIRSXGYR AYQKSXROI URMAR MQ PSPWIB LC RRI KSRGCXPI JMB GMXWGNIPKXGYR MP EUKVBC  WM  GLYD EPO CME AYSXGXK DYV',

 'TSWGD XFO SDPMASEJ GIZCMRO SD TEL LLYQMBKVG DS NKVRSGGZERO ML DLGC GMWTCDMRSSL NEW LC BKC RRI DBIQR EGB SD DLC ORTSVMXQCXX GC KCDXGXK NYPJEXCN FCMESCI MP XFO QGHMLQ SD ZEPDMAEPYDIQ  LMMVSESGYV QMVIAEP',

 'CC  ELN SRRIP REPWJSV QYDIPSEJC  WSML NYPJEXCN EGB MQ MESCMLQ LCKPRR TPYFJOQQ  NMQOEQOW YXH BOERR  EGB TMVPSDMMX MQ YRC YJ RRI KYWR SQNYVRKRR ORTSVMXQCXXYV MQCYCC AFSGF BIOEMPOW RY FC XSRSGCN ELN WMVZ',
 'CN FW DLC OJDYVRC SD KPJ YJ SC  ML YVBOV RY MLMVCKWC KAYBILOWQ KQMXK QDYBORRC EZYYR DLGC MQCYC  KMP ZSJVYRSSL OWQKC FKW ZOGMWI YX MKZSPDELD XMZMA PSP DLC OWQKC UBMRSRE MSKZIRSXGYR  QY WREHCXXQ ISS KVC',

 'KX PSKFD TJKGC  TYQD KM KLCKH  QEGF OWQKC MX EGB TMVPSDMMX AGVP FOPN ISS DS USR CCWYI APSXGXK AYQNOXGDMMX FCMESCI YVP YBI UBMRDIL SR TOVW CMKZPC OREVMQR PYXKSKKC EWGXK CKWW GSPNW  YSV NYPJEXGYR GC E K',

 'YWR CIPSSSC TPYFJOQ MP XFO GSBVCXX RSQC KPJ YZCB XFO AMBPB OWNOGGKPJI ML DLC VEPQI ASXGOW ZOGYEWC YJ RRI FEKC VITOP MP MLNYQDVGKPGJERSSL  DLC BIJOEQO SD CYAR EGB TMVPSDELDW GX LCKZW MSLMILDVYDMMXW QE',

 'TYBXGMYJKXCC  WMVMB WEROVGKPQ  OXA KVC QIRDMLQ WCDXJOH MFIP DLC MMRI  GYEWGXK YSV NYPJEXGYR YXH FOEJDL FKDYBHQ DS RRI NOSNVI  JYXQ YJ BSVRI AYCXCC TPYHSMIB LC NOSNVI MX HYSPW LEQSW CCTCMMYVPW SR RRI Z',

 'SK ASXGOW NYPJEXGXK RRI URSJO ERWSQZLCBMA KMP DS Y QVCKX CHXCXX  YSV NYPJEXGYR GC XFO QGHMLQ SD KRW REPWJSV WSLWRKRAOW RY XFO ERWSQZLCBI DBIQR EGB GYEWGXK FEKC VITOP MP HYWEEOW  FEQYX LCKPRR HGCSPNIPC',

 'VCNYASRE DLC AYYVMRI SD VMDO  IRM  EGB TMVPSDMMX MQ SRABIYCMLQ HYI FW NEW LIAKYQO SD DLC SRABIYCMLQ RSWFCB SD SRBEWRBMCC  WSML NYPJEXCN EGB RCFIP BIKKMLC ER YRC ZPYMI FYACFIP CTPOEB DS URSJO ILFMPYRK',

 'WILD ELN EDPIADMLQ XFO PGFIQ YJ RRI NOSNVI YVP RRVMEKF DLC GSPVH  BOERR VYDIQ YJ RRI FEQYX FCSREC LYFI ZOIL SRABIYCIB LIAKYQO SD SRABIYCIB FEPSIRI SD NMQOEQOW  RRI NYPJEXCN EGB AC LVCKXFO ITOVW WSKORR',

 'MESCMLQ PSXKQ NMQYVBOVQ KRB OZCX PSXK AKRAOV RRYQ KJDOGRSRE DLC RIYVXF YJ MDLCB FMNC MBKYXW  YSV NYPJEXGYR GC GMXXGXYMEWJI HYWEESRE DLC GLMVI CMSJYKGMEJ CCQDIK KRB KJDOGRSRE DLC VMTOW MP TJKRRC ELN EL',

 'SQYVW YC ACVP  GD LYC VCKGFOH RY XFO GPSXGMEJ CXYQI YXH YPJCMXGXK RRI URSJO ERWSQZLCBI ZI EJVSUSRE WSPO LYBQDEP PKHGKXGYRQ PVMW XFO WSX XM DLC OEPDL  YQEGX TMVPSDIB KMP KGRC EQ K FCDXCB MLCYJKXMB AFSGF',

 'ZVCFILDW FOER DS EOX CCGYZIB LEAU MLDS RRI QZEAO  EGB TMVPSDMMX MQ YRC YJ RRI KKML ORTSVMXQCXXYV MQCYCC RMGEBKCQ  DLCBI YBI KKRW BIYCSLC FCRMLN VCQYJKVJI MLMVCKWGXK RRMQ KMP ZSJVYRSSL  WSQD SD DLC KMP',

 'ZSJVYRSSL SW AKYQOH ZI XFO ESDSKYFGVIQ  DVYXWNYVR WIYXW  GXHSCXPSEJSDYDMMX  KPYAGXK ASXGOW  CDG  RRI POPCKWC YJ QOZCBEJ REPWJSV KYCIQ YV BKREOVMEW CVIKORRC JPYQ QEGF CSSBGCC MQ MESCMLQ XFO AFYPC KXKYW',

 'NRIPSG YSV NYPJEXGYR  MJSLO PYIIP SW YVWM QIRDMLQ EDPIADIB DSM WYAR FW DLC KMP ZSJVYRSSL GLGML AKYQOW QOVGYYQ NMQDYPLELMIQ DS RRI CXZGBSLWILD  MLMVCKWGXK LOIB YJ RRI CFIP QVMGMLQ LSWEL ZSNEPYDMMX MQ W',

 'EGX GYEWC YJ NYPJEXGYR  BKMJI LSWEL LIGXK YMXGFMRSIQ MESCMLQ HYXKCBSSC GFOQGMEJC XM BIJOEQO  QYUMLQ ERWSQZLCBI BSVRSIP DLYX ITOV YXH DYVASRE DLC MPGWERO GFKREO RCQERSZCVC  GXHSCXPSEJSDYDMMX TPYGCCW PO',

 'PCKWCC QYXC FKVKPYJ QEQOW  NKVRSGJOW  NKMLD ELN FYDXCBMCC GMXXYSRQ VIYN  GGQEPOXROW POPCKWCC GYBFMX QMXSVSHC  DVYXWNYVR WIYXW POPCKWCC GM  KRB YXFOV RYBGM WSLWRKRAOW RY XFO ERWSQZLCBI  YVP RRI NYPJEXY',

 'XXQ KVC LIGXK GX GMXXYMX USXF DLC KXKYWNRIPO  HCCXPYCGXK RRI MJSLO PYIIP KRB MEJVMLQ LYBQDEP PKCQ YJ QER RY XFO IYBXF  SR MBHCB XM BIBEGC DLC VITOP MP EGB TMVPSDMMX AC CLMEPB LVGXK QYQC RYEO GFKREOW R',

 'Y SSB LYLMRC SL NEGVC ZKWGC  AC CLMEPB XSR MYR DVCOW  SCI NEFJSG RBELCTMBXYDMMX  ETYMB CTPKC AKRQ  KRB CS KKRW KGRSZGDMCC ML DLC PETYV RY VCNYAO XFO IDPIADW MP EGB TMVPSDMMX  EGB TMVPSDMMX MQ DLC WMVS',

 'RE YJ DYVCSKL CYZCXYXGCC XM DLC GLMVI YDQMCTFOVGM EGB  LYBQDEP YXH RYBGM KYCIQ OQGDXCN FW DLC SRBEWRBMCC ELN QMDSP FIFSGJOW AKYQSRE RYEO HYWEEO XM DLC VMTSRE YVEKRGCQQ GLCDLCB TJKRRC  ELSQYVW MB LSWEL',

 'LIGXKQ  CSKO SD DLC XEREVYV ELN ZYBMMEW FEQYX VCCSSBGCC EPO GYEWGXK YSV NYPJEXGYR  FYACFIP  WSQD SD DLC KMP ZSJVYRSSL CSSBGCC EPO WROQ MEX MP XFO LSWEL KGRSZGDMCC PGUI ZEVLSRE PSQCMJ PYCVW  AYEJ KRB Y',

 'SJSP  POPCKWC YJ FKVKPYJ QEQOW YXH QEFQDELMIQ PVMW JYMXMBMCC ELN QMDSP FIFSGJOW  QEGF REPWJSV GFOQGMEJ MSKZSSXHQ VMIO GYBFMX HGYBGNI  LSXPYKCX SVSHCC  GYBFMX QMXSVSHC  CYJZLSB HGYBGNI  QYPGN TYBXGMPCC',

 'IRM EPO KCDXGXK KSBCN XM DLC PVCCL YSV  RRI JOZCV SD KMP ZSJVYRSSL REQ LIAYQC SRABIYCIB LC EBIYD IVDILD FCMESCI MP    MLMVCKWC SR BKQYQMLQ TMVPSDELDW ZOGYEWC YJ RRI CHTYXHCN RCOH MP QMDSP FIFSGJOW DBS',

 'K VEQD GCXXSBC MDLCB WMEVAO SD DLC KMP ZSJVYRSSL SW BOGMWTMCMRSSL YJ EKVZKKC SR JKRBPMJVW YXH BSWNYWYV SD CSJSH UKWROW URMAR EPO IKSXRSRE WIRRELO KYC  HYXKCBSSC XM DLC RIYVXF   BENSH EBSUDL MP TMZYJKX',
 'LSSL  SRBEWRBMYVMXKXGYR  GXGPOEQOH SCI MP ESDSKYFGVIQ  KIPYTJKRCC  IRM LYC QYNI RRMQ SWQEI Y CIPSSSC ILFMPYRKORRKP NBSZVIK  DLC KMP GI ZBIYDLC OZCBC KYQCXX GC JSVP MP TMVPSDELDW EYMLQ XM YYP VYLQW YXH',

 'URSJO FMNC RRVMEKF LPMYH AKYQSRE ERAYYLDEZVI FOEJDL NBSZVIKC  TMVPSDIB KMP SW AKYQSRE NEKKKC DS RRI NVELDW  YXMKKPQ KRB RYKKR ZOMLQW GX QYXC BSVCMX YXH GXHGBIAD AYIW  GP XFO ILFMPYRKORRKP NBSROGRSSL Z',

 'SJSGGOW YBI LYX DYPJYACN WCBMMEWJI ELN WRBMADPW  DLC SRABIYCMLQ PCFIJ YJ YSV NYPJEXGYR KKC GXGPOEQO YN DS MXI KSPJSSL DSLC ELXYYVPW SR RRI POGCXX BOGYNIQ GLCX XFO JPOWF KMP QIRC TMVPSDIB LC KOELC SD N',

 'YQD  XMHMA QEQOW  QWSIO  QMDSP FIFSGJOW  KSPJC ELN JYMXMBMCC  IRM GYVPCN EGB TMVPSDMMX  EQ GI YVP IXSU DLYD JPOWF KMP SW RRI KYWR SQNYVRKRR OPCWILD SD DLC RIYVXFI PGPI  UO RCOH RY XFSRI DLYD AFKX FKTN',

 'ORQ SJ URSJO ERWSQZLCBMA KMP QIRC HGBXW  PMPCX MP EJV EGB TMVPSDMMX MQ DLC WERDIP YJ EBIYD VCQVCD JMB XFO AFYPC RYKKR DBEROVLSXW  CSKO SD DLC LME BIYCSLC SD DLC KMP ZSJVYRSSL KVC EWC YJ NYMQYRMEW DOVR',

 'SPGJIPC  MLCIADMASHCC  TCCXGMMBOW GX XFO EEBMAEPREVYV WCMXMBW ZI XFO MLXSAORR PEPWIPC ML YVBOV RY MLMVCKWC DLC MVMZ TPYHSMXGYR  POPCKWCN GFOQGMEJC ELN LYJEPNSSC KYCIQ  KQKYRGK  JPYQ QEGF PIPDMJSDCBW Y',

 'BI EOXRSRE WMVOH GXXM DLC PVCCL YSV YXH AKYQSRE KMP ZSJVYRSSL LYPXMLQ SD PSQCMJ PYCVW QEGF KW AYEJ  ZIRBSJOYK SRAVYBSRE YXFOV DKGRYVW MSKLYQDMZVIQ KVC DLC WEHYV AKYQOW MP EGB TMVPSDMMX  ZYBMCDC MP WKY',

 'OC OQGCWGYRQ PVMW XFO ESDSKYFGVIQ CYAR EQ MEPC  FSCIQ  WSRYVAIGJOW  RBYAUW  HOINC  XPKMLC  ECBSNVELOW  CDG YBI YVWM MESCMLQ EGB TMVPSDMMX  MLMVCKWGXK LEQZOV MP MLNYQDVGOW GC GYEWGXK POPCKWC YJ RYBGM M',

 'LNYQDVGKP QWSIOW YXH FKVKPYJ QEQOW  JSOC MEPLSL WSLYBGNI  MBKYXMA MSKZSSXHQ  RCBBSAKVZYRQ  MLCWMAKPQ  OXA  PVMW XFO JYMXMBMCC ELN QGVPQ DS RRI CXZGBSLWILD  WMWI GXHMYV YMXGFMRSIQ YJ RRI NOSNVI JSOC SR',

 'LXSAORR EWC YJ AVIYXMLQ TPYHSMXQ  GEQRMLQ TMGHCBW  NKMLDW CDG CWMRC ZYBMMEW RYBGM GFOQGMEJC XM DLC KMP  DLC OZCB MLMVCKWGXK JOZCV SD KMP ZSJVYRSSL KPQY ILRELMIQ SXQ XIEKXGFI YXH FKVKPYJ OJDOGRC XM DLC',

 'RIYVXF YJ JSZGXK ZOMLQW  YSV NYPJEXGYR GC GYEWGXK EVSZKP UKVKSRE DS GXGPOEQO FCMESCI MP MLMVCKWGXK YDQMCTFOVGM XCWTCBEREVC NYC DS RRI GXGPOEQSRE VITOP MP KPOIL RSSCI EKWCC  WSML EBICX LMEWC QEQOW YQEG',
 'X GYEWGXK EBICX LMEWC OJDOGR KRB PSPMMLQ WCK PCFIJC XM SRABIYCI  EVEASIPC XM WIJD  ACKXFOV RY GFKREO  GJSQYDI RY GFKREO  IRM  MLMVCKWGXK YSV NYPJEXGYR GC GYEWGXK KKRW VIRREJ NMQOEQOW  AKRAOV  FOEPD ER',

 'DEAU  EQDLKK  FPYRARMRSW  ISHLOC BSWCKWCC  IRM  ELN HCKXF DS MMGSB  ZYBMMEW GWTMBXYXX YXMKKPQ KRB ZPYXXQ CTCMMCC LYFI ZOIL NIQDVMIIB MSKZPCDIJI JPYQ RRMQ ZPYXIR  SRABIYCMLQ PCFIJ YJ FKVKPYJ QEQOW GX X',

 'FO ILFMPYRKORR KVC MESCMLQ XFO SAMYPBILMI MP EASH PKML KRB NINVIRSRE DLC YDMXI JKCCB  MLMVCKWGXK AYRAORRBERSSL YJ RRI FKVKPYJ KRB DSVSG KKXCBMYVW GX XFO JPOWF KMP YJ RRI YDQMCTFOVC SW AKYQSRE KMP ZSJV',

 'YRSSL  FEPSIRI SD PSPOMEX TYBXGMPCC  XMHMA QEQOW YXH MDLCB TMVPSDELDW POPCKWCN JPYQ TKVGYYQ RYKKR YMXGFMRSIQ KVC KJDOGRSRE DLC PVCCL YSV URMAR LYC EBFIPCI CPJCMX RY XFO PGFMLQ FCSREC PGUI FEQYX FCSREC',

 'ELSQYVW YXH NVELDW  RRI JOZCV SD KMP ZSJVYRSSL NINORBC SL DLC DCNO ELN EKYYLD SD ZSJVYRKRRC VCVIYCIB PVMW ZYBMMEW QYYPMIQ  DSNYKPKTFSGYV ELN QCDIMBSJYKGMEJ MSLNMRSSLC EPO MLMVCKWGXK RRI QZVCKH YXH AYR',

 'AORRBERSSL YJ RRI NYPJEXYXXQ  FEPSIRI SD BEU WEROVGKPQ EWCN ML DLC WELEJYMXSBMLQ TPYGCCW GX MLNYQDVGOW GC MLMVCKWGXK RRI RITC KRB AYYXXSW SD OQGCWGYRQ YJ FKVKPYJ QEQOW  GXGPOEQSRE ZSNEPYDMMX HCXWGDC G',

 'C HCWELNMLQ XFO RCOH MP QMBI GXHSCXPSEJSDYDMMX AFSGF EPRSQYDIJI GYEWCC EGB TMVPSDMMX  EGB TMVPSDELDW JSOC REPWJSV PGAYGN HPYTJOXQ  CSJSHQ ZEPDMAEPYDIQ  KRB DSVSG EKWCC ELN EGB WKYOC MESCMLQ WKYK YXH F'
]
#Labels=[np.zeros((50,27)),np.ones((50,27))]
Labels = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
target =[0, 0 ,0 ,0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
#0->SS
#1->Vignere

def get_dataSet_and_labels():
	vectorizer=CountVectorizer(analyzer='char')
	data_set_fit = vectorizer.fit_transform(Data_set)
	data_set_fit = data_set_fit.todense(2)
	data_set_fit = np.array(data_set_fit,dtype=float)
	test_data= ['OB RCA ICAYX YOMU DC LCYVU HE OTZCPDHED LCJOHY ZPCKYUT ISOYU ICPMOEF IODS DSU YHDULD DUJSECYCFR HEX YUHPEOEF BPCT OEJPUXOKYU TUEDCPL IU SHVU H ZPCNUJD BCP RCA DSOL ZPCNUJD JHYYUX JUYULDOEO ZPCNUJD SHL','JHAFSD DSU OEDUPULD CB AEXUPFPHXL BPCT KCDS OEXOH HEX AFHEXH CAP ZPCNUJD BCJALUL CE ALOEF THJSOEU YUHPEOEF HEX XHDH HEHYRDOJL CE H EUDICPM CB OCD CP TCKOYU XUVOJUL DC LCYVU OTZCPDHED LCJOCUJCECTOJ ZPC','KYUTL LAJS HL PCHX LHBUDR HOP ZCYYADOCE IHDUP WAHYODR ISUPU DSU XHDH JCYYUJDUX BPCT LUELCPL LAJS HL VOXUC JHTUPHL HOP IHDUP WAHYODR LUELCPL OL ALUX OE PUHY DOTU DC THMU OEBUPUEJUL AZXHDU TCXUYL HEX FU','HYUPDL DSU THPJCEO LCJOUDR OL H BCAEXHDOCE XUXOJHDUX DC KUEUBODOEF THEMOEX DSPCAFS LJOUEDOBOJ HJSOUVUTUEDL OE DSU OEDUPEUD HEX JCTTAEOJHDOCEL UHJS RUHP IU PUJCFEOGU H FPCAZ CB OELZOPHDOCEHY FPHXAHDU P','ULUHPJSUPL IODS DSU RCAEF LJSCYHP HIHPX CAP RCAEF LJSCYHPL HPU ZHLLOCEHDU HKCAD ICPMOEF IODS LDAXUEDL OE XUVUYCZOEF JCAEDPOUL DC SUYZ LCYVU OTZCPDHED LCJOHY ZPCKYUTL DSOL ICPM JHYYUX DSU JUYULDOEO ZPC','NUJD SHL LAJJULLBAYYR OTZPCVUX DSU SUHYDS CB ZPUFEHED ICTUE OE AFHEXH HEX UQZHEXUX DC OEXOH OE ZHPDEUPLSOZ IODS OOD XUYSO UHJS ZHPDOJOZHDOEF DUHT TALD KU JCTZPOLUX CB DIC BCAP AEXUPFPHXAHDU LDAXUEDL U','EPCYYUX HD HE OEXOHE UEFOEUUPOEF OELDODADOCE DSU DUHT JHE HYLC OEVCYVU H BHJAYDR TUEDCP BPCT DSUOP OELDODADOCE DSU DUHT TALD HPPHEFU UWAOZTUED HD DSUOP CIE JCLD BCP ZSHLU O DC ZHPDOJOZHDU ZYUHLU LAKTO','D RCAP DUHT XUDHOYL DC DSOL YOEM BCP WAULDOCEL ZYUHLU UTHOY JUYULDOEOZPOGUOEXOH HD FTHOY XCD JCT ZSHLU O IU IOYY FOVU H DHMU SCTU UQHT JCTZPOLOEF CB JCXOEF ZYAL CZUE UEXUX XULOFE WAULDOCEL CE H THPJS','IUUMUEX DIC ZHPDOJOZHEDL BPCT UHJS DUHT TALD DHMU DSU UQHT BCP DSUOP DUHT DC WAHYOBR UHJS DUHT IOYY LAKTOD H XCJATUED CE DSUOP ZPCZCLUX HZZPCHJS DC LCYVOEF ZPCKYUTL HPCAEX DSUTU FOVUE KR CPFHEOGUPL ZS','H LU OO DSU LUYUJDUX DUHTL IOYY OEDUPE HD OOD XUYSO BCP DSPUU TCEDSL KUDIUUE THR HEX LUZ UHJS DUHT IOYY JCTZPOLU DIC DC BCAP TUTKUPL HEX UHJS LDAXUED DUHT TUTKUP IOYY PUJUOVU H LDOZUEX CB XCYYHP DIC S', 'TK XZZ VZZKO QHVJ SZ XNWAD LS HXUNCYZYY RZHHLQ OCTAWJL HMHWJ VZWJTSF HNSS YGP QZEJRE YDNMMZQNRD ZYI KPFQYNMR KQZR HYHQPIHMQD XJMETQD BD SFUP F OCTIPHS QTQ JTT EMHD UQZODNY BLQKPI BPQDDYHYN OCTIPHS SFR','NFTRMS EMD TSSPWDDY NQ ZMOJQRWZOX ECTL MTSS NMONZ LSC FLZYIZ ZZQ AWNUJBE KNNZRPX NY ZRTSF XFBSNMP QDLWMTSF LSC OFSL FMLQXENBD TM L SDEBNCP NQ NNE TQ XTATQD OJUTHDD YN DTKGJ HXUNCYZYY RZHHZJBZSNXNB AWN','MQDXX RFHG LX QZFC DFEPYX LNQ ATKWZSTTM HFSPW PFFKTYX HMDCJ SSJ CLYZ NTKWJBEJC QWNX XDYXNCX RFHG LX UTIDZ HZXJQLX ZTW VLYDC VTLQHED RPSRZWR TX TDJC TS QPFK ENLP YN XFJP NMQJQPSBPX TAIZEJ LZIDWX ZYI FP','LQDCYR EMD XFQNTMT XNNNDED HD F EZZMOFSTTM OJCTHZEJC ET APSDQNSTSF XFMVNMO YGCTTRM RNNDYYHQNB LHGTJUPRDYYR TS SSJ HYYDCSDE FMO HNXRTYNBLYHZSR PFBS DDLW VP WDNTFYNYP F FCTTA TE TSRANQLYHZSZW LQLITLYD C','PXDLWBSJQD BHEM SSJ XZZMR XBSTKLW ZHFQO TTC DNFSF DHGZQZCX ZCJ OLXRTTMLYD LGNFY VZWJTSF HNSS XSFIDYYR TS CPADWTOTSF NTTYYQTJR ET GPQO DTKGJ HXUNCYZYY RZHHLQ OCTAWJLD YGTX VZWJ NFKWJC EMD NJKPXSTSH AWN','UJBE MZD XTNHDDXEFQKJ NLAWNGJC EMD SJZWYG ZK OCJFYFME BNXJM TS TRFMOF ZYI DIUZYIDO YN TSCTF HY UZCYMPWRSNO HNSS NHE IDWMH PFBS UZCYHNNOLYHYL SPFL XZRE GD NTLAWHDJC ZK SHT EZZQ FSCPWFCFCFFSP XSFIDYYR P','YWNWQDO FS LS HYIHLS DYLHYJDCNMR NMDYHEZSTTM EMD EJZX HZY FKDT HYANWAD L KZNZKED LPSSZW ECTL EMDTW HYXSTYTENNY YGP YDLR LFXS LWQLSFP JPFNOXJME FS EMDTW NHS BZXS QTQ AMZDJ H ET OLWSTHHAFSP UKPFRP XTMRH','E DNFW SPFL OJSLNKD YN EMHD QHYP EZW PFJRENNYX OWJZDJ DXFHW HDWJRENMTUQTEDTSCTF ZE LLLNK OTS NTL AMZDJ H HJ VTQK RNUP F SLPD STLP JWLR BZROCNRTSF ZK BZIHYL OWZR ZUDY JMOJC OJRTLM BZDDYHZSR ZS Z XFQNM','HJDVJMO YVZ UZCYHNNOLSSD KQZR DLHG EJZX RTDY SLPD EMD PCZX KNC YGPNQ EJZX YN BZZWNEJ JZNM SPFL HNKW XTMRHE F CZHTXJME TM EMDTW OCTOZXDO FOAWNLHG ET RZQUTSF AWNMQDXX ZCTTYI SSJLP LHGJM MD NCLZYNYPWR AM','L XD TN SSJ RPQDNYDO YDLRR HNKW NMEJQY FS TNS OJKSN EZW SSWDP RNYYGD GDEBDPS LLD ZYI RPU DLHG EJZX BHWQ BZROCNRP YVZ YN QTTC RDXGDCX ZYI DLHG DYTOJME YDLR LPRAPW VTQK CJBPNUP F RENOPSC ZK CZQKLW SHT G']
	data_test= vectorizer.fit_transform(test_data)
	data_test = data_test.todense(2)
	data_test = np.array(data_test,dtype=float)
	
	global Labels
	new_label = np.array(Labels,dtype=float)
	global target
	target = np.array(target,dtype=float)
	#replicating the data to create a larger training dataset.
	new_set = np.concatenate((data_set_fit,data_set_fit),axis=0)
	new_label = np.concatenate((new_label,new_label),axis=0)
	for i in range(3):
		new_set = np.concatenate((new_set,new_set),axis=0)
		new_label = np.concatenate((new_label,new_label),axis=0)
	return new_set,new_label,data_test,target


def main():

	data_set_fit,Labels,data_test,target =get_dataSet_and_labels()

	SGD_clf = SGDClassifier(loss='perceptron', penalty='elasticnet', alpha= 0.00001,random_state=42,warm_start=True)
	for i in range(10):
		SGD_clf.fit(data_set_fit,Labels)

	predict = SGD_clf.predict(data_test)

	print(np.mean(predict==target))
	print(predict)
main()


